### ISSUE TITLE
Migrate code to the terraform-aws-modules/terraform-aws-rds-aurora and publish in the registry

### ISSUE THREAD

**Issue by antonbabenko** [terraform-community-modules/tf_aws_aurora#3]
Hi @hakamadare and @tfhartmann,

Could you please migrate this module to https://github.com/terraform-aws-modules/terraform-aws-rds-aurora ?

Send pull-requests, and we discuss the process as we go. This module is a good candidate to be very feature-rich and powerful. Look into https://github.com/terraform-aws-modules/terraform-aws-rds for inspiration, it has similar types of resources.

Maybe we should even implement Aurora as submodule inside RDS module right away? What do you think?

Thanks,
Anton.

**Comment by ozbillwang** [comment]
@antonbabenko 

The reason I don't use yours ( https://github.com/terraform-aws-modules/terraform-aws-rds-aurora) is because that repo doesn't take care of `aws_db_parameter_group` and `aws_rds_cluster_parameter_group` and the codes of `parameters` (https://www.terraform.io/docs/providers/aws/r/db_parameter_group.html#parameter)

Currently this old repo has no updated for a while, especially after 0.12.x. I did an upgrade on my fork, you can take a reference, if you want to improve yours. 

https://github.com/ozbillwang/tf_aws_aurora

```
variable "cluster_parameters" {
  description = "A list of cluster parameter maps to apply"
  type        = list(map(string))
  default     = []
}

variable "db_parameters" {
  description = "A list of db parameter maps to apply"
  type        = list(map(string))
  default     = []
}

resource "aws_rds_cluster_parameter_group" "aurora_cluster_parameter_group" {
  name        = local.name
  family      = var.family
  description = "Terraform-managed cluster parameter group for ${local.name}"

  dynamic "parameter" {
    for_each = var.cluster_parameters
    content {
      apply_method = lookup(parameter.value, "apply_method", null)
      name         = parameter.value.name
      value        = parameter.value.value
    }
  }

  tags = merge(
    local.common_tags,
    {
      "Name" = local.name
    },
  )
}

resource "aws_db_parameter_group" "aurora_parameter_group" {
  name        = local.name
  family      = var.family
  description = "Terraform-managed parameter group for ${local.name}"

  dynamic "parameter" {
    for_each = var.db_parameters
    content {
      apply_method = lookup(parameter.value, "apply_method", null)
      name         = parameter.value.name
      value        = parameter.value.value
    }
  }

  tags = merge(
    local.common_tags,
    {
      "Name" = local.name
    },
  )
}
```

**Comment by ozbillwang** [comment]
By the way, the reason I don't raise PR to merge it to current upstream is, 

I redefine some variables, especially the name. This repo hards codes a lot on the naming, which I totally don't like the way.

**Comment by antonbabenko** [comment]
This repository has been deprecated and will not be updated.

Interested people are already using and contributing to https://github.com/terraform-aws-modules/terraform-aws-rds-aurora , and I completely agree that some parameters are not configurable enough (improving one module at the time).

I also have 24 hours in a day :)
