### ISSUE TITLE
I am not able pass the parameters with name and value. Is there a format that i need to pass the parameters of db_parameter_group in variables

### ISSUE THREAD

**Issue by ghost** [terraform-community-modules/tf_aws_aurora#6]
https://github.com/terraform-community-modules/tf_aws_aurora/blob/5db62f5092562fa85a66724e8236ad1b4b74dbc8/main.tf#L57

**Comment by antonbabenko** [comment]
I see you opened similar issue in more up-to-date repository - https://github.com/terraform-aws-modules/terraform-aws-rds/issues/28 . Closing this issue, because this module is not properly maintained anymore.
